<?php
//namespace WooBonusPlus_API;

defined('ABSPATH') || exit; // Exit if accessed directly

class WooBonusPlus_API
{
    
    public static function bp_api_request($endpoint, $params, $type)
    {
        if ( empty($endpoint) || empty($type) )
            return;
        
        $url = 'https://bonusplus.pro/api/' . $endpoint;
        
        if ( !empty($params) & is_array($params) ){
            foreach ($params as $key=>$value){
                $url = add_query_arg( [$key=>$value], $url );
            }
        }

        $option = get_option('woobonusplus_option_name');
        $token = $option['_api_2'];
        $token = base64_encode($token);
        
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $type);


        $headers = array();
        //$headers[] = 'Authorization: ApiKey NjU4QUQ2MjAtMTkzNS00NDUzLTg1RjgtNTg4MDlGRUQzMEZD';
        $headers[] = 'Authorization: ApiKey '.$token;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            error_log( 'Error:' . curl_error($ch) );
        }
        curl_close($ch);

        return $result;
    }
}

