<?php
//namespace WooBonusPlus_API;

defined('ABSPATH') || exit; // Exit if accessed directly

class WooBonusPlus_API
{
    private $url = 'https://bonusplus.pro/lk';
    private $header = 'ApiKey';

    public static function init(){
        // login to bonusplus
    }
    
    public static function bp_api_get_login(){
        /**
         * curl --location --request GET 'https://bonusplus.pro/api/account' \
         *  --header 'Authorization: ApiKey NjU4QUQ2MjAtMTkzNS00NDUzLTg1RjgtNTg4MDlGRUQzMEZD'
         */
        $remote_get = wp_remote_get($url, array(
            'timeout'     => 5,
            'redirection' => 5,
            'httpversion' => '1.0',
            'headers'     => array(
                'Accept'        => 'application/json',
                'Content-Type'  => 'application/json',
                'Authorization' => 'Bearer ' . $id_token,
            ),
        ));
    }

    public static function bp_api_get_login_curl(){
        
        $option = get_option('woobonusplus_option_name');
        $login = $option['_0'];
        $pass = $option['_1'];
        $token = $option['_api_2'];

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://bonusplus.pro/api/account');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        // NjU4QUQ2MjAtMTkzNS00NDUzLTg1RjgtNTg4MDlGRUQzMEZD
        $token = base64_encode($token);
        $headers = array();
        $headers[] = 'Authorization: ApiKey '. $token;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            $result = 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }

    public static function bp_api_get_customer_data_curl($user_id=''){
        if ( empty($user_id) ){
            $user_id = get_current_user_id();
        }
        $phone = '+79119387283';
        $url = 'https://bonusplus.pro/api/customer?phone=' . $phone;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Authorization: ApiKey NjU4QUQ2MjAtMTkzNS00NDUzLTg1RjgtNTg4MDlGRUQzMEZD';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }

    public static function bp_api_request($endpoint, $params, $type)
    {
        if ( empty($endpoint) || empty($type) )
            return;
        
        $url = 'https://bonusplus.pro/api/' . $endpoint;
        if ( !empty($params) & is_array($params) ){
            foreach ($params as $key=>$value){
                $url = add_query_arg( [$key=>$value], $url );
            }
        }

        $option = get_option('woobonusplus_option_name');
        $token = $option['_api_2'];
        $token = base64_encode($token);
        
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $type);


        $headers = array();
        //$headers[] = 'Authorization: ApiKey NjU4QUQ2MjAtMTkzNS00NDUzLTg1RjgtNTg4MDlGRUQzMEZD';
        $headers[] = 'Authorization: ApiKey '.$token;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            error_log( 'Error:' . curl_error($ch) );
        }
        curl_close($ch);

        return $result;
    }
}
//WooBonusPlus_API::init();

